name: build-nix
run-name: Blobs build - Nix

on: [push, pull_request]

jobs:
  build_changes:
    strategy:
      matrix:
        arch: [ARM64, X64]
    name: build_changes
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: install nix
        uses: cachix/install-nix-action@v20
      - name: build artifacts
        run: nix-build --pure -A all
